#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: #@ data.values.resource_group + '-' + data.values.vault_name
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: #@ "https://" + data.values.vault_name + ".vault.azure.net"
      serviceAccountRef:
        name: workload-identity-sa
        namespace: #@ data.values.platform_ops_namespace

