#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-3-good-secret
  namespace: app-3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: #@ data.values.resource_group + '-' + data.values.vault_name
  target:
    name: app-3-secret-1
  data:
  - secretKey: value
    remoteRef:
      key: app-3-secret-1
